# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'myreactnativeapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for myreactnativeapp
  pod 'AppCenter/Crashes', '~> 1.6.0'
  pod 'AppCenter/Analytics', '~> 1.6.0'
  pod 'AppCenterReactNativeShared', '~> 1.5.0'

  

  platform :ios, '9.0'
  target 'myreactnativeappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'myreactnativeapp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for myreactnativeapp-tvOS

  target 'myreactnativeapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
